using System;

[Serializable]
public class Achievements
{
	public enum achievements
	{
		ONENIGHTATFREDDYS,
		TWONIGHTSATFREDDYS,
		THREENIGHTSATFREDDYS,
		FOURNIGHTSATFREDDYS,
		FIVENIGHTSATFREDDYS,
		OVERTIME,
		NOTAMPERING,
		NORUNNING,
		NOLAUGHING,
		NOHIDING,
		THEBYTEOF87,
		WITHEREDBONNIEGAMING
    }
}
